package GUI;

import data.Destination;
import data.DestinationManager;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class CreateDestination extends javax.swing.JDialog {

    private UserInterface userInterface;
    private DestinationManager destinationManager;

    /**
     * Creates new form CreateDestination
     *
     * @param userInterface
     */
    public CreateDestination(UserInterface userInterface) {
        initComponents();
        destinationManager = DestinationManager.getTheDestinationManager();
        this.userInterface = userInterface;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateDestination = new javax.swing.JDialog();
        textNameDestination = new javax.swing.JTextField();
        textCostDestination = new javax.swing.JTextField();
        textTypeDestination = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelNameDestination = new javax.swing.JLabel();
        labelTypeDestination = new javax.swing.JLabel();
        labelCostDestination = new javax.swing.JLabel();
        buttonCancelDestination = new javax.swing.JButton();
        buttonSaveDestination = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        CreateDestination.setResizable(false);

        javax.swing.GroupLayout CreateDestinationLayout = new javax.swing.GroupLayout(CreateDestination.getContentPane());
        CreateDestination.getContentPane().setLayout(CreateDestinationLayout);
        CreateDestinationLayout.setHorizontalGroup(
            CreateDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );
        CreateDestinationLayout.setVerticalGroup(
            CreateDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        textNameDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameDestinationActionPerformed(evt);
            }
        });

        textTypeDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTypeDestinationActionPerformed(evt);
            }
        });

        jLabel1.setText("Create Destination");

        labelNameDestination.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNameDestination.setText("Name:");

        labelTypeDestination.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTypeDestination.setText("Type:");

        labelCostDestination.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCostDestination.setText("Cost:");

        buttonCancelDestination.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonCancelDestination.setText("Cancel");
        buttonCancelDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelDestinationActionPerformed(evt);
            }
        });

        buttonSaveDestination.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonSaveDestination.setText("Save");
        buttonSaveDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveDestinationActionPerformed(evt);
            }
        });

        jLabel2.setText("2 - 20 characters");

        jLabel3.setText("2 - 20 characters");

        jLabel4.setText("under 10.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTypeDestination, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCostDestination, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNameDestination, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSaveDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancelDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textNameDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textTypeDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textCostDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNameDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNameDestination)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTypeDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTypeDestination)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCostDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCostDestination)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSaveDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameDestinationActionPerformed

    private void textTypeDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTypeDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTypeDestinationActionPerformed

    private void buttonCancelDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelDestinationActionPerformed
        setVisible(false);
        textNameDestination.setText("");
        textCostDestination.setText("");
        textTypeDestination.setText("");
    }//GEN-LAST:event_buttonCancelDestinationActionPerformed

    private void buttonSaveDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveDestinationActionPerformed

        if (textNameDestination.getText().isEmpty() || textTypeDestination.getText().isEmpty()
                || textCostDestination.getText().isEmpty()) {
            JOptionPane.showMessageDialog(userInterface, "Please enter all fields!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Destination newDestination = checkNewDestination();
            if (newDestination != null) {
                destinationManager.addDestination(newDestination);
                setVisible(false);
                userInterface.getContentPane().repaint();
                textNameDestination.setText("");
                textCostDestination.setText("");
                textTypeDestination.setText("");
            }
        }
    }//GEN-LAST:event_buttonSaveDestinationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CreateDestination;
    private javax.swing.JButton buttonCancelDestination;
    private javax.swing.JButton buttonSaveDestination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCostDestination;
    private javax.swing.JLabel labelNameDestination;
    private javax.swing.JLabel labelTypeDestination;
    private javax.swing.JTextField textCostDestination;
    private javax.swing.JTextField textNameDestination;
    private javax.swing.JTextField textTypeDestination;
    // End of variables declaration//GEN-END:variables

    private Destination checkNewDestination() {
        Destination newDestination;
        int destinationID = destinationManager.getNextDestinationID();
        // 9000 IDs is the maximum, which can be stored
        if (destinationID > 9000) {
            JOptionPane.showMessageDialog(this, "Maximum Limit of destinations!", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        String dName = textNameDestination.getText().trim();
        String dType = textTypeDestination.getText().trim();
        Double dCost;
        textNameDestination.setBackground(new Color(255, 255, 255));
        textTypeDestination.setBackground(new Color(255, 255, 255));
        textCostDestination.setBackground(new Color(255, 255, 255));

        if (!isValidDName(dName)) {
            JOptionPane.showMessageDialog(userInterface, "Only letters are allowed, and two consecutive spaces are not allowed.\nAnd/Or incorrect characters", "Invalid Name!", JOptionPane.ERROR_MESSAGE);
            textNameDestination.setBackground(new Color(255, 102, 102));
            return null;
        }

        if (!isValidDType(dType)) {
            JOptionPane.showMessageDialog(userInterface, "Only letters are allowed, and two consecutive spaces are not allowed.\nAnd/Or incorrect characters", "Invalid Type!", JOptionPane.ERROR_MESSAGE);
            textTypeDestination.setBackground(new Color(255, 102, 102));
            return null;
        }

        try {
            dCost = Double.valueOf(textCostDestination.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "The cost field should exclusively consist of numerical values!\nPlease correct", "Invalid Cost!", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (dCost <= 0) {
            JOptionPane.showMessageDialog(this, "Cost is too low!\nEnter a positive value under 10000!", "Invalid Cost!", JOptionPane.ERROR_MESSAGE);
            return null;
        } else if (dCost > 10000) {
            JOptionPane.showMessageDialog(this, "Cost is too high!\nEnter a positive value under 10000!", "Invalid Cost!", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        newDestination = new Destination(destinationID, dName, dType, dCost);
        return newDestination;
    }

    private boolean isValidDName(String dName) {
        return dName.matches("[A-Za-z]+(\\s[A-Za-z]+)*") && dName.length() >= 2 && dName.length() <= 20;
    }

    private boolean isValidDType(String dType) {
        return dType.matches("[A-Za-z]+(\\s[A-Za-z]+)*") && dType.length() >= 2 && dType.length() <= 20;
    }

}
