package GUI;

import data.Trip;
import data.TripManager;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class CreateTrip extends javax.swing.JDialog {

    private UserInterface userInterface;
    private TripManager tripManager;

    // variable so user cant select 7 and 14 at the same time
    private Integer selectedDuration;

    /**
     * Creates new form CreateTrip
     */
    public CreateTrip(UserInterface userInterface) {
        tripManager = TripManager.getTheTripManager();
        this.userInterface = userInterface;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNameTrip = new javax.swing.JTextField();
        textTypeTrip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelNameTrip = new javax.swing.JLabel();
        labelTypeTrip = new javax.swing.JLabel();
        labelDurationTrip = new javax.swing.JLabel();
        buttonCancelTrip = new javax.swing.JButton();
        buttonSaveTrip = new javax.swing.JButton();
        textCostTrip = new javax.swing.JTextField();
        labelCostTrip = new javax.swing.JLabel();
        checkBoxSieben = new javax.swing.JCheckBox();
        checkBoxVierzehn = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        textNameTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameTripActionPerformed(evt);
            }
        });

        textTypeTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTypeTripActionPerformed(evt);
            }
        });

        jLabel2.setText("Create Trip");

        labelNameTrip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNameTrip.setText("Name:");

        labelTypeTrip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTypeTrip.setText("Type:");

        labelDurationTrip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDurationTrip.setText("Duration:");

        buttonCancelTrip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonCancelTrip.setText("Cancel");
        buttonCancelTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelTripActionPerformed(evt);
            }
        });

        buttonSaveTrip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonSaveTrip.setText("Save");
        buttonSaveTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveTripActionPerformed(evt);
            }
        });

        labelCostTrip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCostTrip.setText("Cost:");

        checkBoxSieben.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxSieben.setText("7");
        checkBoxSieben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSiebenActionPerformed(evt);
            }
        });

        checkBoxVierzehn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxVierzehn.setText("14");
        checkBoxVierzehn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxVierzehnActionPerformed(evt);
            }
        });

        jLabel4.setText("under 10.000");

        jLabel3.setText("2 - 20 characters");

        jLabel5.setText("2 - 20 characters");

        jLabel1.setText("days");

        jLabel6.setText("days");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDurationTrip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTypeTrip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNameTrip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCostTrip, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textNameTrip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTypeTrip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCostTrip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(buttonSaveTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancelTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxSieben, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(checkBoxVierzehn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(87, 87, 87)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNameTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNameTrip)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTypeTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTypeTrip)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCostTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCostTrip)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDurationTrip)
                    .addComponent(checkBoxSieben, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxVierzehn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSaveTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTypeTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTypeTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTypeTripActionPerformed

    private void buttonCancelTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelTripActionPerformed
        setVisible(false);
        textNameTrip.setText("");
        textCostTrip.setText("");
        textTypeTrip.setText("");
        checkBoxSieben.setSelected(false);
        checkBoxVierzehn.setSelected(false);
    }//GEN-LAST:event_buttonCancelTripActionPerformed

    private void buttonSaveTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveTripActionPerformed
        if (textNameTrip.getText().isEmpty() || textTypeTrip.getText().isEmpty()
                || textCostTrip.getText().isEmpty() || selectedDuration == null) {
            JOptionPane.showMessageDialog(userInterface, "Please enter all fields!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Trip newTrip = checkNewTrip();
            if (newTrip != null) {
                tripManager.addTrip(newTrip);
                setVisible(false);
                userInterface.getContentPane().repaint();
                textNameTrip.setText("");
                textCostTrip.setText("");
                textTypeTrip.setText("");
                checkBoxSieben.setSelected(false);
                checkBoxVierzehn.setSelected(false);
            }
        }
    }//GEN-LAST:event_buttonSaveTripActionPerformed

    private void textNameTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameTripActionPerformed

    private void checkBoxVierzehnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxVierzehnActionPerformed
        if (checkBoxVierzehn.isSelected()) {
            checkBoxSieben.setSelected(false);
            selectedDuration = 14; // 14 selected
        } else {
            selectedDuration = null; // nothing selected
        }
    }//GEN-LAST:event_checkBoxVierzehnActionPerformed

    private void checkBoxSiebenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSiebenActionPerformed
        if (checkBoxSieben.isSelected()) {
            checkBoxVierzehn.setSelected(false);
            selectedDuration = 7; // 7 selected
        } else {
            selectedDuration = null; // nothing selected
        }
    }//GEN-LAST:event_checkBoxSiebenActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelTrip;
    private javax.swing.JButton buttonSaveTrip;
    private javax.swing.JCheckBox checkBoxSieben;
    private javax.swing.JCheckBox checkBoxVierzehn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelCostTrip;
    private javax.swing.JLabel labelDurationTrip;
    private javax.swing.JLabel labelNameTrip;
    private javax.swing.JLabel labelTypeTrip;
    private javax.swing.JTextField textCostTrip;
    private javax.swing.JTextField textNameTrip;
    private javax.swing.JTextField textTypeTrip;
    // End of variables declaration//GEN-END:variables

    private Trip checkNewTrip() {
        Trip newTrip;
        int tripID = tripManager.getNextTripID();
        // 9000 IDs is the maximum, which can be stored
        if (tripID > 9000) {
            JOptionPane.showMessageDialog(this, "Maximum Limit of trips!", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        String tName = textNameTrip.getText().trim();
        String tType = textTypeTrip.getText().trim();
        Double tCost;
        textNameTrip.setBackground(new Color(255, 255, 255));
        textTypeTrip.setBackground(new Color(255, 255, 255));
        textCostTrip.setBackground(new Color(255, 255, 255));

        if (!isValidTName(tName)) {
            JOptionPane.showMessageDialog(userInterface, "Only letters are allowed, and two consecutive spaces are not allowed.\nAnd/Or incorrect characters", "Invalid Name!", JOptionPane.ERROR_MESSAGE);
            textNameTrip.setBackground(new Color(255, 102, 102));
            return null;
        }

        if (!isValidTType(tType)) {
            JOptionPane.showMessageDialog(userInterface, "Only letters are allowed, and two consecutive spaces are not allowed.\nAnd/Or incorrect characters", "Invalid Type!", JOptionPane.ERROR_MESSAGE);
            textTypeTrip.setBackground(new Color(255, 102, 102));
            return null;
        }
        
        try {
            tCost = Double.valueOf(textCostTrip.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "The cost field should exclusively consist of numerical values!\nPlease correct", "Invalid Cost!", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (tCost <= 0) {
            JOptionPane.showMessageDialog(this, "Cost is too low!\nEnter a positive value under 10000!", "Invalid Cost!", JOptionPane.ERROR_MESSAGE);
            return null;
        } else if (tCost > 10000) {
            JOptionPane.showMessageDialog(this, "Cost is too high!\nEnter a positive value under 10000!", "Invalid Cost!", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        Integer tDuration = selectedDuration;

        newTrip = new Trip(tripID, tName, tType, tCost, tDuration);
        return newTrip;
    }
    
    private boolean isValidTName(String tName) {
        return tName.matches("[A-Za-z]+(\\s[A-Za-z]+)*") && tName.length() >= 2 && tName.length() <= 20;
    }

    private boolean isValidTType(String tType) {
        return tType.matches("[A-Za-z]+(\\s[A-Za-z]+)*") && tType.length() >= 2 && tType.length() <= 20;
    }

}
