package GUI;

import data.Settings;
import javax.swing.JButton;

/**
 *
 * @author ahmed
 */
public class DialogAbout extends javax.swing.JDialog {
    Settings settings;
    /**
     * Creates new form DialogAbout
     */
    
    public DialogAbout() {
        settings = Settings.getTheSettings();
        initComponents();
        updateLabels();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProgramAbout = new javax.swing.JLabel();
        labelLincenseeAbout = new javax.swing.JLabel();
        closeAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setResizable(false);

        labelProgramAbout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelProgramAbout.setText("jLabel1");

        labelLincenseeAbout.setText("jLabel2");

        closeAbout.setText("Close");
        closeAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelProgramAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLincenseeAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeAbout)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelProgramAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeAbout)
                    .addComponent(labelLincenseeAbout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeAboutActionPerformed

    public JButton getcloseAbout() {
        return closeAbout;
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeAbout;
    private javax.swing.JLabel labelLincenseeAbout;
    private javax.swing.JLabel labelProgramAbout;
    // End of variables declaration//GEN-END:variables
    
    public void updateLabels(){
        labelProgramAbout.setText(settings.getProgramName() + " " + settings.getProgramVersion());
        labelLincenseeAbout.setText(settings.getLicenseeName());
    }
}
