package GUI;

import data.Trip;
import data.TripManager;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author ahmed
 */
public class IFrameTrip extends javax.swing.JInternalFrame implements TableModelListener {

    private TableTrip tableTrip;
    private CreateTrip createTrip;
    private TripManager tripManager;
    private static IFrameTrip iFrameTrip;
    private static UserInterface userInterface;

    /**
     * Creates new form IFrameTrip
     *
     * @param userInterface
     */
    public IFrameTrip(UserInterface userInterface) {
        tableTrip = new TableTrip();
        IFrameTrip.userInterface = userInterface;
        tripManager = TripManager.getTheTripManager();
        initComponents();
        tableTripManager.getModel().addTableModelListener(this);
    }
    
    public static IFrameTrip getTheIFrameTrip(){
        iFrameTrip = new IFrameTrip(userInterface);
        return iFrameTrip;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tableTripManager = new javax.swing.JTable();
        labelTripTitle = new javax.swing.JLabel();
        buttonCreateTrip = new javax.swing.JButton();
        buttonDeleteTrip = new javax.swing.JButton();
        buttonMainMenuTrip = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        tableTripManager.setModel(tableTrip);
        tableTripManager.setFillsViewportHeight(true);
        tableTripManager.getTableHeader().setReorderingAllowed(false);
        tableTripManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTripManagerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableTripManagerMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tableTripManager);

        labelTripTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTripTitle.setText("Trip Manager");

        buttonCreateTrip.setText("New");
        buttonCreateTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateTripActionPerformed(evt);
            }
        });

        buttonDeleteTrip.setText("Delete");
        buttonDeleteTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteTripActionPerformed(evt);
            }
        });

        buttonMainMenuTrip.setText("< Main Menu");
        buttonMainMenuTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainMenuTripActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("*to update simply select and edit the properties");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMainMenuTrip)
                .addGap(297, 297, 297)
                .addComponent(labelTripTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCreateTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDeleteTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMainMenuTrip)
                    .addComponent(labelTripTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateTrip)
                    .addComponent(buttonDeleteTrip)
                    .addComponent(jLabel11))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTripManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTripManagerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableTripManagerMouseClicked

    private void tableTripManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTripManagerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableTripManagerMouseEntered

    private void buttonCreateTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateTripActionPerformed
        if (createTrip == null) {
            createTrip = new CreateTrip(userInterface);
        }
        createTrip.setVisible(true);
    }//GEN-LAST:event_buttonCreateTripActionPerformed

    private void buttonDeleteTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteTripActionPerformed
        int pos = tableTripManager.getSelectedRow();
        int max = tableTripManager.getRowCount();
        if (pos < 0 || pos >= max) {
            return;
        }
        Trip trip = tripManager.getTrip(pos);
        int option = JOptionPane.showConfirmDialog(this, "" + trip, "Really delete this trip?", JOptionPane.YES_NO_OPTION);
        if (option != JOptionPane.YES_OPTION) {
            return;
        }
        tripManager.deleteTrip(trip);
        getContentPane().repaint();
    }//GEN-LAST:event_buttonDeleteTripActionPerformed

    private void buttonMainMenuTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuTripActionPerformed
        if (createTrip != null) {
            createTrip.setVisible(false);
        }
        this.setVisible(false);
    }//GEN-LAST:event_buttonMainMenuTripActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateTrip;
    private javax.swing.JButton buttonDeleteTrip;
    private javax.swing.JButton buttonMainMenuTrip;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelTripTitle;
    private javax.swing.JTable tableTripManager;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        Trip newTrip = tripManager.getTrip(row);
        try {
            tripManager.updateTrip(newTrip);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this,
                    exc,
                    "Please Correct",
                    JOptionPane.ERROR_MESSAGE);
        }
        getContentPane().repaint();
    }
    
    public javax.swing.JTable getTableTripManager(){
        return tableTripManager;
    }

}
