package GUI;

import data.Destination;
import data.DestinationManager;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author ahmed
 */
public class IFrameDestination extends javax.swing.JInternalFrame implements TableModelListener {

    private TableDestination tableDestination;
    private CreateDestination createDestination;
    private DestinationManager destinationManager;
    private static IFrameDestination iFrameDestination;
    private static UserInterface userInterface;
    
    /**
     * Creates new form IFrameDestination
     * @param userInterface
     */
    public IFrameDestination(UserInterface userInterface) {
        tableDestination = new TableDestination();
        IFrameDestination.userInterface = userInterface;
        destinationManager = DestinationManager.getTheDestinationManager();
        initComponents();
        tableDestinationManager.getModel().addTableModelListener(this);
    }
    
    public static IFrameDestination getTheIFrameDestination(){
        iFrameDestination = new IFrameDestination(userInterface);
        return iFrameDestination;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCreateDestination = new javax.swing.JButton();
        labelDestinationTitle = new javax.swing.JLabel();
        buttonMainMenuDestination = new javax.swing.JButton();
        buttonDeleteDestination = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDestinationManager = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(671, 358));
        setVisible(true);

        buttonCreateDestination.setText("New");
        buttonCreateDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateDestinationActionPerformed(evt);
            }
        });

        labelDestinationTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDestinationTitle.setText("Destination Manager");

        buttonMainMenuDestination.setText("< Main Menu");
        buttonMainMenuDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainMenuDestinationActionPerformed(evt);
            }
        });

        buttonDeleteDestination.setText("Delete");
        buttonDeleteDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteDestinationActionPerformed(evt);
            }
        });

        tableDestinationManager.setModel(tableDestination);
        tableDestinationManager.setFillsViewportHeight(true);
        tableDestinationManager.getTableHeader().setReorderingAllowed(false);
        tableDestinationManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDestinationManagerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableDestinationManagerMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tableDestinationManager);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("*to update simply select and edit the properties");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMainMenuDestination)
                .addGap(266, 266, 266)
                .addComponent(labelDestinationTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCreateDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDeleteDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMainMenuDestination)
                    .addComponent(labelDestinationTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateDestination)
                    .addComponent(buttonDeleteDestination)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDestinationManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDestinationManagerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDestinationManagerMouseClicked

    private void tableDestinationManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDestinationManagerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDestinationManagerMouseEntered

    private void buttonCreateDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateDestinationActionPerformed
        if (createDestination == null) {
            createDestination = new CreateDestination(userInterface);
        }
        createDestination.setVisible(true);
    }//GEN-LAST:event_buttonCreateDestinationActionPerformed

    private void buttonDeleteDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteDestinationActionPerformed
        int pos = tableDestinationManager.getSelectedRow();
        int max = tableDestinationManager.getRowCount();
        if (pos < 0 || pos >= max) {
            return;
        }
        Destination destination = destinationManager.getDestination(pos);
        int option = JOptionPane.showConfirmDialog(this, "" + destination, "Really delete this destination?", JOptionPane.YES_NO_OPTION);
        if (option != JOptionPane.YES_OPTION) {
            return;
        }
        destinationManager.deleteDestination(destination);
        getContentPane().repaint();
    }//GEN-LAST:event_buttonDeleteDestinationActionPerformed

    private void buttonMainMenuDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuDestinationActionPerformed
        if (createDestination != null) {
            createDestination.setVisible(false);
        }
        this.setVisible(false);
    }//GEN-LAST:event_buttonMainMenuDestinationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateDestination;
    private javax.swing.JButton buttonDeleteDestination;
    private javax.swing.JButton buttonMainMenuDestination;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDestinationTitle;
    private javax.swing.JTable tableDestinationManager;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        Destination newDestination = destinationManager.getDestination(row);
        try {
            destinationManager.updateDestination(newDestination);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this,
                    exc,
                    "Please Correct",
                    JOptionPane.ERROR_MESSAGE);
        }
        getContentPane().repaint();
    }
    
    public javax.swing.JTable getTableDestinationManager(){
        return tableDestinationManager;
    }

}
