package GUI;

import data.Settings;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class IFrameSettings extends javax.swing.JInternalFrame {

    private UserInterface userInterface;
    private Settings settings;

    public IFrameSettings(UserInterface userInterface) {
        this.userInterface = userInterface;
        initComponents();
        settings = Settings.getTheSettings();
        settingsProgramName.setText(settings.getProgramName().trim());
        settingsProgramVersion.setText(settings.getProgramVersion().trim());
        settingsLicensee.setText(settings.getLicenseeName().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        settingsProgramName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        settingsProgramVersion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        settingsLicensee = new javax.swing.JTextField();
        settingsCancel = new javax.swing.JButton();
        settingsSave = new javax.swing.JButton();
        labelCharacterlimitProgramName = new javax.swing.JLabel();
        labelCharacterlimitProgramVersion = new javax.swing.JLabel();
        labelCharacterlimitLicensee = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Settings");

        jLabel1.setText("Program Name:");

        settingsProgramName.setToolTipText("");

        jLabel2.setText("Program Version:");

        jLabel3.setText("Licensee:");

        settingsCancel.setText("Cancel");
        settingsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsCancelActionPerformed(evt);
            }
        });

        settingsSave.setText("Save");
        settingsSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsSaveActionPerformed(evt);
            }
        });

        labelCharacterlimitProgramName.setText("2 - 25 characters");

        labelCharacterlimitProgramVersion.setText("1 - 10 characters");

        labelCharacterlimitLicensee.setText("2 - 50 characters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(settingsSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(settingsCancel))
                    .addComponent(settingsProgramName)
                    .addComponent(settingsProgramVersion)
                    .addComponent(settingsLicensee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCharacterlimitProgramName)
                    .addComponent(labelCharacterlimitProgramVersion)
                    .addComponent(labelCharacterlimitLicensee))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(settingsProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCharacterlimitProgramName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(settingsProgramVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCharacterlimitProgramVersion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(settingsLicensee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCharacterlimitLicensee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsSave)
                    .addComponent(settingsCancel))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsSaveActionPerformed
        if (settingsProgramName.getText().isEmpty() || settingsProgramVersion.getText().isEmpty() || settingsLicensee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(userInterface, "Please enter all fields!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String programName = settingsProgramName.getText().trim();
            String programVersion = settingsProgramVersion.getText().trim();
            String licenseeName = settingsLicensee.getText().trim();
            settingsProgramName.setBackground(new Color(255, 255, 255));
            settingsProgramVersion.setBackground(new Color(255, 255, 255));
            settingsLicensee.setBackground(new Color(255, 255, 255));

            // check if input for programName is okay
            if (!isValidProgramName(programName)) {
                JOptionPane.showMessageDialog(userInterface, "Only letters are allowed, and two consecutive spaces are not allowed.\nAnd/Or incorrect characters", "Invalid program name!", JOptionPane.ERROR_MESSAGE);
                settingsProgramName.setBackground(new Color(255, 102, 102));
                return;
            }

            // check if input for programVersion is okay
            if (!isValidProgramVersion(programVersion)) {
                JOptionPane.showMessageDialog(userInterface, "Only numbers and dots are allowed, and two consecutive dots are not allowed.\nAnd/Or incorrect characters", "Invalid program version!", JOptionPane.ERROR_MESSAGE);
                settingsProgramVersion.setBackground(new Color(255, 102, 102));
                return;
            }

            // check if input for licensee is okay
            if (!isValidLicensee(licenseeName)) {
                JOptionPane.showMessageDialog(userInterface, "Only letters and numbers are allowed, and two consecutive spaces are not allowed.\nAnd/Or incorrect characters", "Invalid licensee name! ", JOptionPane.ERROR_MESSAGE);
                settingsLicensee.setBackground(new Color(255, 102, 102));
                return;
            }

            settings.setProgramName(programName);
            settings.setProgramVersion(programVersion);
            settings.setLicenseeName(licenseeName);
            settings.save();
            JOptionPane.showMessageDialog(userInterface, "Program Name: " + programName + "\nProgram Version: " + programVersion + "\nLicensee: " + licenseeName, "saved settings succesfully!", JOptionPane.INFORMATION_MESSAGE);

            // Title of Frame in UserInterface
            userInterface.setTitle(settings.getProgramName() + " " + settings.getProgramVersion());
            this.setVisible(false);
            // the Main Title in UserInterface will display the Program Name
            userInterface.updateTitle();
        }
    }//GEN-LAST:event_settingsSaveActionPerformed

    private boolean isValidProgramName(String programName) {
        return programName.matches("[A-Za-z]+(\\s[A-Za-z]+)*") && programName.length() >= 2 && programName.length() <= 25;
    }

    private boolean isValidProgramVersion(String programVersion) {
        return programVersion.matches("[0-9]+(\\.[0-9]+)*") && programVersion.length() >= 1 && programVersion.length() <= 10;
    }

    private boolean isValidLicensee(String licenseeName) {
        return licenseeName.matches("[A-Za-z0-9]+(\\s[A-Za-z0-9]+)*") && licenseeName.length() >= 2 && licenseeName.length() <= 50;
    }

    private void settingsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsCancelActionPerformed
        this.setVisible(false);
        //setting the names after I canceled it back to what is saved
        settingsProgramName.setText(settings.getProgramName().trim());
        settingsProgramVersion.setText(settings.getProgramVersion().trim());
        settingsLicensee.setText(settings.getLicenseeName().trim());
    }//GEN-LAST:event_settingsCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCharacterlimitLicensee;
    private javax.swing.JLabel labelCharacterlimitProgramName;
    private javax.swing.JLabel labelCharacterlimitProgramVersion;
    private javax.swing.JButton settingsCancel;
    private javax.swing.JTextField settingsLicensee;
    private javax.swing.JTextField settingsProgramName;
    private javax.swing.JTextField settingsProgramVersion;
    private javax.swing.JButton settingsSave;
    // End of variables declaration//GEN-END:variables
}
