package GUI;

import data.DataManager;
import data.Destination;
import data.DestinationManager;
import data.Settings;
import data.Trip;
import data.TripManager;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author ahmed
 */
public class UserInterface extends javax.swing.JFrame {

    DateFormat dateFormat = new SimpleDateFormat("dd/MM/YY");
    Date date = new Date();
    
    private IFrameDestination iFrameDestination;
    private DestinationManager destinationManager;
    private TableDestination tableDestination;
    public java.util.ArrayList<Destination> destinationList;
    
    private IFrameTrip iFrameTrip;
    private TripManager tripManager;
    private TableTrip tableTrip;
    public java.util.ArrayList<Trip> tripList;
    
    Settings settings;

    /**
     * Creates new form MainWIndow
     */
    public UserInterface() {
        tableDestination = new TableDestination();
        destinationManager = DestinationManager.getTheDestinationManager();
        iFrameDestination = IFrameDestination.getTheIFrameDestination();
        destinationList = DestinationManager.getTheDestinationManager().getDestinationList();
        
        tableTrip = new TableTrip();
        tripManager = TripManager.getTheTripManager();
        iFrameTrip = IFrameTrip.getTheIFrameTrip();
        tripList = TripManager.getTheTripManager().getTripList();

        settings = Settings.getTheSettings();
        initComponents();
        updateTitle();
        labelDate.setText(" " + dateFormat.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        labelMainTitle = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBarMain = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemSettings = new javax.swing.JMenuItem();
        MenuDeleteData = new javax.swing.JMenu();
        MenuItemDeleteAll = new javax.swing.JMenuItem();
        MenuItemDeleteDestination = new javax.swing.JMenuItem();
        MenuItemDeleteTrip = new javax.swing.JMenuItem();
        menuItemExitProgramm = new javax.swing.JMenuItem();
        menuBasicData = new javax.swing.JMenu();
        menuItemDestinationManager = new javax.swing.JMenuItem();
        menuItemTripManager = new javax.swing.JMenuItem();
        menuItemEmployeeManager = new javax.swing.JMenuItem();
        menuItemBusManager = new javax.swing.JMenuItem();
        menuItemHotelManager = new javax.swing.JMenuItem();
        menuItemServiceManager = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemHelp = new javax.swing.JMenuItem();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Main Menu");
        setName("MainWindow"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        labelMainTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        labelMainTitle.setText("Dreamland Travel");

        labelVersion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVersion.setText("Basic Data Management 1.0 Copyright © 2023 Ahmed Ali, MNR 327698");

        labelDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDate.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Date:");

        menuFile.setText("FILE");
        menuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemSettings.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemSettings.setText("Settings");
        menuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSettingsActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSettings);

        MenuDeleteData.setText("Delete Data");
        MenuDeleteData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenuItemDeleteAll.setText("Delete All");
        MenuItemDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeleteAllActionPerformed(evt);
            }
        });
        MenuDeleteData.add(MenuItemDeleteAll);

        MenuItemDeleteDestination.setText("Delete Destination");
        MenuItemDeleteDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeleteDestinationActionPerformed(evt);
            }
        });
        MenuDeleteData.add(MenuItemDeleteDestination);

        MenuItemDeleteTrip.setText("Delete Trip");
        MenuItemDeleteTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeleteTripActionPerformed(evt);
            }
        });
        MenuDeleteData.add(MenuItemDeleteTrip);

        menuFile.add(MenuDeleteData);

        menuItemExitProgramm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemExitProgramm.setText("Exit Programm");
        menuItemExitProgramm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitProgrammActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExitProgramm);

        menuBarMain.add(menuFile);

        menuBasicData.setText("BASIC DATA");
        menuBasicData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemDestinationManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemDestinationManager.setText("Manage destinations");
        menuItemDestinationManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDestinationManagerActionPerformed(evt);
            }
        });
        menuBasicData.add(menuItemDestinationManager);

        menuItemTripManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemTripManager.setText("Manage trips");
        menuItemTripManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTripManagerActionPerformed(evt);
            }
        });
        menuBasicData.add(menuItemTripManager);

        menuItemEmployeeManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemEmployeeManager.setText("Managing employees");
        menuItemEmployeeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmployeeManagerActionPerformed(evt);
            }
        });
        menuBasicData.add(menuItemEmployeeManager);

        menuItemBusManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemBusManager.setText("Managing busses");
        menuItemBusManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBusManagerActionPerformed(evt);
            }
        });
        menuBasicData.add(menuItemBusManager);

        menuItemHotelManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemHotelManager.setText("Manage hotels");
        menuItemHotelManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHotelManagerActionPerformed(evt);
            }
        });
        menuBasicData.add(menuItemHotelManager);

        menuItemServiceManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemServiceManager.setText("Manage services");
        menuItemServiceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemServiceManagerActionPerformed(evt);
            }
        });
        menuBasicData.add(menuItemServiceManager);

        menuBarMain.add(menuBasicData);

        menuHelp.setText("HELP");
        menuHelp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemHelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Help.png"))); // NOI18N
        menuItemHelp.setText("Help");
        menuItemHelp.setName(""); // NOI18N
        menuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHelpActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemHelp);

        menuItemAbout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        menuBarMain.add(menuHelp);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(labelVersion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelMainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVersion))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitProgrammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitProgrammActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemExitProgrammActionPerformed

    private void menuItemDestinationManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDestinationManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemDestinationManagerActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemTripManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTripManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemTripManagerActionPerformed

    private void menuItemEmployeeManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmployeeManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEmployeeManagerActionPerformed

    private void menuItemBusManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBusManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBusManagerActionPerformed

    private void menuItemHotelManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHotelManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemHotelManagerActionPerformed

    private void menuItemServiceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemServiceManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemServiceManagerActionPerformed

    private void menuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHelpActionPerformed
        JOptionPane.showMessageDialog(this,
                "This Program manages Destinations and Trips. \n Further Objects are not yet implemented!",
                "Help",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemHelpActionPerformed

    private void menuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSettingsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void MenuItemDeleteDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeleteDestinationActionPerformed
        int option = JOptionPane.showOptionDialog(this,
                "Are you sure you want to delete all destinations data?\nThis data can´t be restored!",
                "Delete Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Yes","No"},
                "No");
        
        if (option == JOptionPane.YES_OPTION) {
            deleteAllDestinationData();;
        }
    }//GEN-LAST:event_MenuItemDeleteDestinationActionPerformed

    private void MenuItemDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeleteAllActionPerformed
        int option = JOptionPane.showOptionDialog(this,
                "Are you sure you want to delete all data?\nThe data can´t be restored!",
                "Delete Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Yes","No"},
                "No");
        
        if (option == JOptionPane.YES_OPTION) {
            deleteAllData();
        }
    }//GEN-LAST:event_MenuItemDeleteAllActionPerformed

    private void MenuItemDeleteTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeleteTripActionPerformed
        int option = JOptionPane.showOptionDialog(this,
                "Are you sure you want to delete all trips data?\nThe data can´t be restored!",
                "Delete Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Yes","No"},
                "No");
        
        if (option == JOptionPane.YES_OPTION) {
            deleteAllTripData();
        }
    }//GEN-LAST:event_MenuItemDeleteTripActionPerformed

    private void deleteAllData() {
        //deleting destinations
        destinationManager.deleteAllDestination();
        iFrameDestination = new IFrameDestination(this);
        this.getDesktopPane().add(iFrameDestination);
        try {
            iFrameDestination.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
        iFrameDestination.setVisible(false);
        
        // deleting trips
        tripManager.deleteAllTrip();
        iFrameTrip = new IFrameTrip(this);
        this.getDesktopPane().add(iFrameTrip);
        try {
            iFrameTrip.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
        iFrameTrip.setVisible(false);
        JOptionPane.showMessageDialog(this, "All Data deleted succesfully!");
    }
    
    private void deleteAllDestinationData(){
        destinationManager.deleteAllDestination();
        iFrameDestination = new IFrameDestination(this);
        this.getDesktopPane().add(iFrameDestination);
        try {
            iFrameDestination.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
        iFrameDestination.setVisible(false);
        JOptionPane.showMessageDialog(this, "Destinations Data deleted succesfully!");
    }
    
    private void deleteAllTripData(){
        tripManager.deleteAllTrip();
        iFrameTrip = new IFrameTrip(this);
        this.getDesktopPane().add(iFrameTrip);
        try {
            iFrameTrip.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
        iFrameTrip.setVisible(false);
        JOptionPane.showMessageDialog(this, "Trips Data deleted succesfully!");
    }

    public JMenuItem getMenuItemDeleteTrip() {
        return MenuItemDeleteTrip;
    }

    public void setMenuItemDeleteTrip(JMenuItem MenuItemDeleteTrip) {
        this.MenuItemDeleteTrip = MenuItemDeleteTrip;
    }

    public JMenuItem getMenuItemDeleteAll() {
        return MenuItemDeleteAll;
    }

    public void setMenuItemDeleteAll(JMenuItem MenuItemDeleteAll) {
        this.MenuItemDeleteAll = MenuItemDeleteAll;
    }

    public JMenuItem getMenuItemDeleteDestination() {
        return MenuItemDeleteDestination;
    }

    public void setMenuItemDeleteDestination(JMenuItem MenuItemDeleteDestination) {
        this.MenuItemDeleteDestination = MenuItemDeleteDestination;
    }

    public void updateTitle() {
        labelMainTitle.setText(settings.getProgramName());
    }

    // Getter and Setter, so they can be accessed
    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JMenu getMenuHelp() {
        return menuHelp;
    }

    public void setMenuHelp(JMenu menuHelp) {
        this.menuHelp = menuHelp;
    }

    public JMenuItem getMenuItemAbout() {
        return menuItemAbout;
    }

    public void setMenuItemAbout(JMenuItem menuItemAbout) {
        this.menuItemAbout = menuItemAbout;
    }

    public JMenuItem getMenuItemBusManager() {
        return menuItemBusManager;
    }

    public void setMenuItemBusManager(JMenuItem menuItemBusManager) {
        this.menuItemBusManager = menuItemBusManager;
    }

    public JMenuItem getMenuItemDestinationManager() {
        return menuItemDestinationManager;
    }

    public void setMenuItemDestinationManager(JMenuItem menuItemDestinationManager) {
        this.menuItemDestinationManager = menuItemDestinationManager;
    }

    public JMenuItem getMenuItemEmployeeManager() {
        return menuItemEmployeeManager;
    }

    public void setMenuItemEmployeeManager(JMenuItem menuItemEmployeeManager) {
        this.menuItemEmployeeManager = menuItemEmployeeManager;
    }

    public JMenuItem getMenuItemExitProgramm() {
        return menuItemExitProgramm;
    }

    public void setMenuItemExitProgramm(JMenuItem menuItemExitProgramm) {
        this.menuItemExitProgramm = menuItemExitProgramm;
    }

    public JMenuItem getMenuItemHelp() {
        return menuItemHelp;
    }

    public void setMenuItemHelp(JMenuItem menuItemHelp) {
        this.menuItemHelp = menuItemHelp;
    }

    public JMenuItem getMenuItemHotelManager() {
        return menuItemHotelManager;
    }

    public void setMenuItemHotelManager(JMenuItem menuItemHotelManager) {
        this.menuItemHotelManager = menuItemHotelManager;
    }

    public JMenuItem getMenuItemServiceManager() {
        return menuItemServiceManager;
    }

    public void setMenuItemServiceManager(JMenuItem menuItemServiceManager) {
        this.menuItemServiceManager = menuItemServiceManager;
    }

    public JMenuItem getMenuItemSettings() {
        return menuItemSettings;
    }

    public void setMenuItemSettings(JMenuItem menuItemSettings) {
        this.menuItemSettings = menuItemSettings;
    }

    public JMenuItem getMenuItemTripManager() {
        return menuItemTripManager;
    }

    public void setMenuItemTripManager(JMenuItem menuItemTripManager) {
        this.menuItemTripManager = menuItemTripManager;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuDeleteData;
    private javax.swing.JMenuItem MenuItemDeleteAll;
    private javax.swing.JMenuItem MenuItemDeleteDestination;
    private javax.swing.JMenuItem MenuItemDeleteTrip;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelMainTitle;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBasicData;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemBusManager;
    private javax.swing.JMenuItem menuItemDestinationManager;
    private javax.swing.JMenuItem menuItemEmployeeManager;
    private javax.swing.JMenuItem menuItemExitProgramm;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemHotelManager;
    private javax.swing.JMenuItem menuItemServiceManager;
    private javax.swing.JMenuItem menuItemSettings;
    private javax.swing.JMenuItem menuItemTripManager;
    // End of variables declaration//GEN-END:variables

}
